#!/bin/bash

# A simple but powerful CLI tool to automate k8s deployment of Pi-hole on a Pi (or elsewhere potentially)

ARGS=$*

export PRINT_PREFIX="Kube Pi Hole"

source scripts/utils.sh

no_args() {
    print_assistant "Error! You must supply at least one argument."
}

#
# Process the args supplied via CLI
#
if [[ $ARGS == 0 ]]; then
    no_args
else
    # At least one arg supplied, process what it is!
    COMMAND=${ARGS}

    print_assistant "Command was supplied ($COMMAND), handling..."

    # this ensures relative paths work and we execute from the root of the repo
    # cd "$HOME/KubePiHole"

    if [[ $COMMAND == "install-dependencies" ]]; then
        source scripts/install-required-packages.sh

        print_assistant "Installing depencies via helper, it will output useful info..."
        install_dependencies
    fi
fi
