#!/bin/bash

# A simple but powerful CLI tool to automate k8s deployment of Pi-hole on a Pi (or elsewhere potentially)

ARGS=$*

export PRINT_PREFIX="Kube Pi Hole"

# Contains a few helpful methods because I like DRY things
source scripts/colours.sh
source scripts/utils.sh

no_args() {
    print_assistant "Error! You must supply at least one argument."
}

#
# Process the args supplied via CLI
#
if [[ $ARGS == 0 ]]; then
    no_args
else
    # At least one arg supplied, process what it is!
    COMMAND=${ARGS}

    print_assistant "Kube Pi Hole is running!" "title" "Command was supplied: $COMMAND"

    # this ensures relative paths work and we execute from the root of the repo
    cd "$HOME/KubePiHole"

    if [[ $COMMAND == "install-dependencies" || $COMMAND == "install" ]]; then
        source scripts/install-required-packages.sh

        print_assistant "Installing depencies via helper, it will output useful info..."
        install_dependencies
    elif [[ $COMMAND == "deploy" ]]; then
        source scripts/deploy.sh

        print_assistant "Deploying the k8s manifests now with automatic env substition..."

        deploy_pihole
    fi

    space_terminal_lg
fi
