---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${PIHOLE_NAME}
  name: ${PIHOLE_NAME}
  namespace: ${KUBE_NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PIHOLE_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${PIHOLE_NAME}
        name: ${PIHOLE_NAME}
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.8"
            memory: "1G"
          requests:
            cpu: "0.5"
            memory: "512M"
        env:
        - name: TZ
          value: "${PIHOLE_TIMEZONE}"
        - name: WEBPASSWORD
          value: "${PIHOLE_WEB_PASSWORD}"
        volumeMounts:
        - name: ${ETC_PERSISTENT_VOLUME}
          mountPath: "${PIHOLE_PATH}"
        - name: ${DNSMASQ_PERSISTENT_VOLUME}
          mountPath: "${DNSMASQ_PATH}"
      volumes:
      - name: ${ETC_PERSISTENT_VOLUME}
        persistentVolumeClaim:
          claimName: ${ETC_PERSISTENT_V_CLAIM}
      - name: ${DNSMASQ_PERSISTENT_VOLUME}
        persistentVolumeClaim:
          claimName: ${DNSMASQ_PERSISTENT_V_CLAIM}