---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PIHOLE_NAME}
  labels:
    app: ${PIHOLE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PIHOLE_NAME}
  template:
    metadata:
      labels:
        app: ${PIHOLE_NAME}
        name: ${PIHOLE_NAME}
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/New_York"
        - name: WEBPASSWORD
          value: "secret"
        volumeMounts:
        - name: ${PIHOLE_NAME}-local-etc-volume
          mountPath: "/etc/${PIHOLE_NAME}"
        - name: ${PIHOLE_NAME}-local-dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: ${PIHOLE_NAME}-local-etc-volume
        persistentVolumeClaim:
          claimName: ${PIHOLE_NAME}-local-etc-claim
      - name: ${PIHOLE_NAME}-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: ${PIHOLE_NAME}-local-dnsmasq-claim