---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PIHOLE_NAME}
  labels:
    app: ${PIHOLE_NAME}
    namespace: ${KUBE_NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PIHOLE_NAME}
  template:
    metadata:
      labels:
        app: ${PIHOLE_NAME}
        name: ${PIHOLE_NAME}
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.8"
            memory: "1G"
          requests:
            cpu: "0.5"
            memory: "512MB"
        env:
        - name: TZ
          value: "${PIHOLE_TIMEZONE}"
        - name: WEBPASSWORD
          value: "${PIHOLE_WEB_PASSWORD}"
        volumeMounts:
        - name: ${PIHOLE_NAME}-local-etc-volume
          mountPath: "/etc/${PIHOLE_NAME}"
        - name: ${PIHOLE_NAME}-local-dnsmasq-volume
          mountPath: "/etc/dnsmasq.d"
      volumes:
      - name: ${PIHOLE_NAME}-local-etc-volume
        persistentVolumeClaim:
          claimName: ${PIHOLE_NAME}-local-etc-claim
      - name: ${PIHOLE_NAME}-local-dnsmasq-volume
        persistentVolumeClaim:
          claimName: ${PIHOLE_NAME}-local-dnsmasq-claim