---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PIHOLE_NAME}-${STORAGE_CLASS_NAME}-etc-volume
  labels:
    directory: etc
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ${STORAGE_CLASS_NAME}
  local:
    path: /${PIHOLE_NAME}/pi-hole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${PIHOLE_NAME}
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PIHOLE_NAME}-${STORAGE_CLASS_NAME}-dnsmasq-volume
  labels:
    directory: dnsmasq.d
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ${STORAGE_CLASS_NAME}
  local:
    path: /${PIHOLE_NAME}/pi-hole
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${PIHOLE_NAME}
          - docker-desktop