---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PIHOLE_NAME}-local-etc-claim
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # recommended in docs as min.
  selector:
    matchLabels:
      directory: etc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PIHOLE_NAME}-local-dnsmasq-claim
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d