---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${ETC_PERSISTENT_VOLUME}
  labels:
    directory: ${PIHOLE_PATH}
spec:
  capacity:
    storage: ${PIHOLE_PV_CAPACITY}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${STORAGE_CLASS_NAME}
  local:
    path: ${PIHOLE_DIR}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${PIHOLE_NAME}
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${DNSMASQ_PERSISTENT_VOLUME}
  labels:
    directory: ${DNSMASQ_PATH}
spec:
  capacity:
    storage: ${DNSMASQ_PV_CAPACITY}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${STORAGE_CLASS_NAME}
  local:
    path: ${DNSMASQ_DIR}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${PIHOLE_NAME}
          - docker-desktop