---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${ETC_PERSISTENT_V_CLAIM}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # recommended in docs as min.
  selector:
    matchLabels:
      directory: etc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${DNSMASQ_PERSISTENT_V_CLAIM}
spec:
  storageClassName: ${STORAGE_CLASS_NAME}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d