---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   metallb.universe.tf/address-pool: network-services
  #   metallb.universe.tf/allow-shared-ip: pihole-svc
  labels:
    app: ${PIHOLE_NAME}
  name: pihole-svc
  namespace: ${PIHOLE_KUBE_NS}
spec:
  # externalTrafficPolicy: Local
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: client-udp
    port: 67
    protocol: UDP
    targetPort: 67
  selector:
    app: ${PIHOLE_NAME}
  sessionAffinity: None
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: pihole-ui-svc
  namespace: ${PIHOLE_KUBE_NS}
  labels:
    app: ${PIHOLE_NAME}
spec:
  selector:
    app: ${PIHOLE_NAME}
  type: NodePort
  ports:
    - name: web-http
      port: 80
      targetPort: 80
      # nodePort: 8008
      protocol: TCP
    - name: web-https
      port: 443
      targetPort: 443
      protocol: TCP