---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${PIHOLE_NAME}
  name: ${PIHOLE_NAME}-public
  namespace: ${KUBE_NS}
spec:
  ports:
    - name: https-web
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dns
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: ${PIHOLE_NAME}
  type: LoadBalancer
status:
  loadBalancer: {}