---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${PIHOLE_NAME}
  name: pihole-tcp
  namespace: ${KUBE_NS}
spec:
  externalTrafficPolicy: Local
  ports:
  - name: dns
    targetPort: dns
    protocol: TCP
    port: 53
    targetPort: dns
  - name: pihole-http
    port: 80
    nodePort: 1001
    protocol: TCP
    targetPort: pihole-http
  selector:
    app: ${PIHOLE_NAME}
  sessionAffinity: None
  type: NodePort