---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${PIHOLE_NAME}
  name: ${PIHOLE_NAME}
  namespace: ${KUBE_NS}
spec:
  replicas: 1
  hostname: ${PIHOLE_NAME}
  selector:
    matchLabels:
      app: ${PIHOLE_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${PIHOLE_NAME}
        name: ${PIHOLE_NAME}
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.8"
            memory: "1G"
          requests:
            cpu: "0.5"
            memory: "512M"
        env:
        - name: FTLCONF_REPLY_ADDR4
          value: ${PIHOLE_IP_ADDRESS}
        - name: TZ
          value: "${PIHOLE_TIMEZONE}"
        - name: WEBPASSWORD
          value: "${PIHOLE_WEB_PASSWORD}"
        securityContext:
          privileged: true
        ports:
          - containerPort: 53
            hostPort: 53
            protocol: TCP
          - containerPort: 53
            hostPort: 53
            protocol: UDP
          - containerPort: 67
            hostPort: 67
            protocol: UDP
          - containerPort: 80
            hostPort: 80
            protocol: TCP
          - containerPort: 443
            hostPort: 443
            protocol: TCP
        volumeMounts:
        - name: etc
          mountPath: "${PIHOLE_PATH}"
        - name: dnsmasq
          mountPath: "${DNSMASQ_PATH}"
      volumes:
      - name: etc
        hostPath:
          path: $PWD/${PERSISTENCE_ETC}
          type: Directory
      - name: dnsmasq
        hostPath:
          path: $PWD/${PERSISTENCE_DNSMASQ}
          type: Directory