---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${PIHOLE_NAME}
  name: ${PIHOLE_NAME}
  namespace: ${KUBE_NS}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PIHOLE_NAME}
  strategy: {}
  template:
    metadata:
      labels:
        app: ${PIHOLE_NAME}
        name: ${PIHOLE_NAME}
    spec:
      hostname: ${PIHOLE_NAME}.pi
      hostNetwork: true
      # dnsPolicy: "None"
      # dnsConfig:
        # nameservers:
          # upstream DNS used by pihole.
          # - 1.1.1.1
          # - 1.0.0.1
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "0.8"
            memory: "1G"
          requests:
            cpu: "0.5"
            memory: "512M"
        env:
        - name: TZ
          value: "${PIHOLE_TIMEZONE}"
        - name: WEBPASSWORD
          value: "${PIHOLE_WEB_PASSWORD}"
        - name: DNSSEC
          value: true
        - name: WEBTHEME
          value: "default-auto"
        - name: PIHOLE_DNS_
          value: 127.0.0.1#5053;1.1.1.1;1.0.0.1
        securityContext:
          privileged: true
        ports:
          - containerPort: 53
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 67
            protocol: UDP
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
        volumeMounts:
        - name: etc
          mountPath: "${PIHOLE_PATH}"
        - name: dnsmasq
          mountPath: "${DNSMASQ_PATH}"
      volumes:
      - name: etc
        hostPath:
          path: $PWD/${PERSISTENCE_ETC}
          type: Directory
      - name: dnsmasq
        hostPath:
          path: $PWD/${PERSISTENCE_DNSMASQ}
          type: Directory