---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pihole-local-storage-etc-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # recommended in docs as min.
  selector:
    matchLabels:
      directory: etc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pihole-local-storage-dnsmasq-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d