---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-kube-local-storage-etc-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      directory: etc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-kube-local-storage-dnsmasq-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: dnsmasq.d